// Original Turkish sentences used to build the synthetic test set (no third-party text).
// Every dotted/dotless i, ç ğ ö ş ü and â occurs many times; `mixed` lines carry digits,
// e-mail addresses, URLs, dates and codes, which is what real CVs and invoices contain.

export const PROSE = [
  'Çocukların bahçede oynadığı güneşli bir öğleden sonra, yaşlı adam bankta oturup gazetesini okuyordu.',
  'Işıklar yandığında sınıftaki öğrencilerin hepsi aynı anda ayağa kalktı ve öğretmenlerini selamladı.',
  "İstanbul Boğazı'nın iki yakasını birleştiren köprüler, şehrin gündelik hayatını belirleyen en önemli yapılardır.",
  'Şirketimiz geçen yıl üç yeni ürün geliştirdi; bunların ikisi yurt dışındaki müşterilerden olumlu geri bildirim aldı.',
  'Doğru yazılmış bir özgeçmiş, işe alım uzmanının dikkatini ilk beş saniyede çekebilmelidir.',
  'Öğrenciler ödevlerini perşembe gününe kadar teslim etmek zorunda; geç gelen çalışmalar değerlendirilmeyecek.',
  'Ağaçların yaprakları sonbaharda sarıya döner, rüzgârın etkisiyle yavaş yavaş yere düşer.',
  'Müşteri şikâyetlerinin büyük bölümü, teslimat süresinin uzaması ve ürün bilgisinin yetersiz olmasından kaynaklanıyor.',
  'Sabahları erken kalkıp yürüyüş yapmak, gün boyu daha enerjik ve üretken olmanızı sağlar.',
  'Yazılım geliştirme sürecinde gereksinimlerin doğru anlaşılması, sonradan yapılacak değişikliklerin maliyetini azaltır.',
  "Ankara'dan İzmir'e giden otobüs, yoğun kar yağışı nedeniyle iki saat gecikmeyle yola çıkabildi.",
  'Bu belgeyi imzalamadan önce tüm maddeleri dikkatlice okumanızı ve sorularınızı bize iletmenizi öneririz.',
  'Küçük bir kasabada büyüyen Ayşe, çocukluğundan beri gökyüzündeki yıldızları merak ederdi.',
  'Toplantı salonunun ışığı kesildiği için sunum, projeksiyon cihazı olmadan sözlü olarak yapıldı.',
  'Güvenlik güncellemeleri uygulanmadığında, sistemdeki açıklar kötü niyetli kişilerce kolayca istismar edilebilir.',
  'Hâlâ eski usul çalışan birçok kurum, belgeleri kâğıt üzerinde saklamayı tercih ediyor.',
  'Yüksek lisans başvurusunda bulunacak adayların not ortalaması en az üç tam yirmi beş olmalıdır.',
  'Gece boyunca süren sağanak yağış, şehrin alçak bölgelerinde sokakların suyla dolmasına yol açtı.',
  'Çalışanların performansı yalnızca rakamlarla değil, ekip içindeki iş birliğiyle de ölçülmelidir.',
  'Mutfaktaki fırından yayılan taze ekmek kokusu, bütün evi sarmış ve herkesi sofraya çağırmıştı.',
  'Öğle yemeğinden sonra başlayan toplantı akşam altıya kadar sürdü, kararların çoğu ertelendi.',
  'Çiftçiler bu yıl kuraklık yüzünden buğday veriminin düşeceğini ve fiyatların artacağını söylüyor.',
  'Ünlü yazarın son romanı, savaş yıllarında ayrı düşen iki kardeşin hikâyesini anlatıyor.',
  'Şu an kullandığınız sürümde ağ ayarlarını değiştirmek için yönetici şifresi girmeniz gerekir.',
  'Gümüş rengi kasası ve ince tasarımıyla dikkat çeken yeni model, önümüzdeki hafta satışa çıkacak.',
  'Her sabah aynı çayı içen komşumuz, bugün nedense kahve istedi ve hepimizi şaşırttı.',
  'Doktorun önerdiği ilacı düzenli kullanmayan hastaların iyileşme süresi belirgin biçimde uzuyor.',
  'Kütüphanedeki sessizlik, sınav haftasında öğrencilerin çalışma verimini gözle görülür şekilde artırdı.',
  'Yeni yılda ücretlerde yüzde on beşlik bir artış yapılması ve ek ödemelerin düzenlenmesi planlanıyor.',
  'Hızlı bir şekilde büyüyen girişim, ilk çeyrekte beklentilerin üzerinde gelir elde ettiğini duyurdu.',
];

export const MIXED = [
  'İletişim: ibrahim.solmaz@ornek.com.tr ; Tel: +90 532 123 45 67 ; Faks: 0212 555 01 02',
  'Fatura No: 2025/00481 ; Tarih: 14.03.2025 ; Vade: 28.03.2025 ; Tutar: 12.450,75 TL',
  'Adres: Çiçek Sokak No: 12/4 Kadıköy / İstanbul 34710',
  'Web: https://www.ornek-sirket.com.tr/hakkimizda ; GitHub: github.com/isolmaz',
  'Sipariş kodu: TR-4471-ŞÇ ; Miktar: 3 adet ; Birim fiyat: 1.299,00 TL ; KDV %20',
  'Doğum tarihi: 02.11.1994 ; Doğum yeri: Gaziantep ; Medeni durum: Bekâr',
  'Toplam 128 sayfa, 14 tablo ve 36 şekil içeren raporun özeti 5 Mayıs 2024 tarihinde yayımlandı.',
  'Python 3.12, Node.js 22, PostgreSQL 16 ve Redis 7 ile geliştirilen servis %99,95 erişilebilirlik sağladı.',
  'Hesap No: TR33 0006 1005 1978 6457 8413 26 ; Şube: Beşiktaş ; Müşteri No: 884 127 903',
  'Sıcaklık 18-24 °C arasında, nem oranı %45-60, rüzgâr hızı 12 km/s olarak ölçüldü.',
];
