#!/usr/bin/env node
/**
 * Phase 4 acceptance harness — throwaway driver, not the e2e suite.
 *
 *   node tools/spikes/phase4-check.mjs [--port 4199] [--keep]
 *
 * What the phase promised:
 *
 *   > a text paragraph is edited → saved → reopened: the new text is searchable,
 *   > the targeted occurrence of the old text is gone (the same string elsewhere in
 *   > the document is untouched), unchanged regions still match, and the visual
 *   > result is within the render-diff tolerance.
 *
 * The driver opens `make-phase4-fixture.mjs`'s document (page 1 carries `KADIKÖY`
 * inside an embedded-subset Turkish paragraph, page 2 carries the same word), runs
 * the edit through the real UI under the production policy, exports the file and
 * reads **the bytes** back with pdf.js in Node — the strongest available statement,
 * because it is the file a reader would open, not the app's own report.
 *
 * Structure-sensitive checks (links, outline, layers, attachments) and the signing
 * check follow the same rule: assert the produced file, not the announcement.
 *
 * Two prerequisites the driver sets rather than hopes for: the browser context is pinned to
 * `tr-TR`, because every label it looks up is Turkish and the app otherwise takes the
 * host's language; and the advanced commands that the simple mode hides (measure,
 * compare, accessibility, batch) are reached only after the run leaves the default simple
 * mode through the header's own switch. A missing Playwright browser fails the run with an
 * install line instead of skipping it: this driver *is* the browser evidence, and a green
 * exit without a browser would report acceptance that never ran.
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as mupdf from 'mupdf';
import { chromium } from 'playwright';
import { readFixture } from './mupdf-fixture.mjs';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const args = process.argv.slice(2);
const readArg = (name, fallback) => {
  const index = args.indexOf(name);
  return index >= 0 ? (args[index + 1] ?? fallback) : fallback;
};
const port = Number.parseInt(readArg('--port', '4199'), 10);
const keepFixture = args.includes('--keep');
const origin = process.env.VERIFY_ORIGIN ?? `http://localhost:${port}`;
const externalServer = process.env.VERIFY_ORIGIN !== undefined;
const FIXTURE_PAGES = 5;
const SENTINEL = 'KADIKÖY';
const REPLACEMENT = 'ÜSKÜDAR';
const CHECK_TIMEOUT_MS = Number.parseInt(process.env.PHASE4_CHECK_TIMEOUT ?? '180000', 10);

if (!existsSync(join(ROOT, 'dist', 'editor', 'index.html'))) {
  console.error(
    'phase4-check: dist/editor/index.html is missing — run `pnpm build && pnpm assemble:dist` first',
  );
  process.exit(1);
}

const fixtureDir = join(tmpdir(), `pdf-editor-phase4-${process.pid}`);

/** The fixture is generated by the repository's own builder — never a committed document. */
function buildFixture() {
  mkdirSync(fixtureDir, { recursive: true });
  const path = join(fixtureDir, 'phase4-fixture.pdf');
  const script = join(ROOT, 'tools', 'spikes', 'make-phase4-fixture.mjs');
  const result = spawn(process.execPath, [script, '--out', path], { cwd: ROOT, stdio: 'inherit' });
  return new Promise((resolve, reject) => {
    result.on('exit', (code) => (code === 0 ? resolve(path) : reject(new Error(`fixture exit ${code}`))));
  });
}

/** Every text page's extracted text, read from the bytes with pdf.js — the reader's own view. */
async function pageTexts(path) {
  const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
  const doc = await pdfjs.getDocument({
    data: new Uint8Array(readFileSync(path)),
    useSystemFonts: false,
    isEvalSupported: false,
    // pdf.js wants a URL *prefix*, trailing separator included; without it the loader
    // rejects the path before it reads anything ("Invalid factory url").
    standardFontDataUrl: `${join(ROOT, 'public', 'engines', 'pdfjs', 'standard_fonts')}/`,
  }).promise;
  const pages = [];
  for (let index = 1; index <= doc.numPages; index += 1) {
    const page = await doc.getPage(index);
    const content = await page.getTextContent();
    pages.push(content.items.map((item) => item.str).join(' '));
  }
  await doc.cleanup();
  return pages;
}

const checks = [];
const consoleErrors = [];
let page = null;
/** The tail of the spawned preview server's output, kept for a failure that has to name it. */
let serverLog = '';

async function recoverFromFailure() {
  try {
    await page.keyboard.press('Escape');
    await page.waitForTimeout(400);
    const open = await page.locator('[role="dialog"]').count();
    if (open > 0) {
      await page.evaluate(() => {
        for (const dialog of document.querySelectorAll('[role="dialog"]')) dialog.remove();
        document.body.style.pointerEvents = '';
      });
    }
    await page.waitForTimeout(200);
  } catch {
    // the tab may be gone; the next check reports it on its own
  }
}

async function check(name, fn, timeoutMs = CHECK_TIMEOUT_MS) {
  const started = Date.now();
  let timer;
  try {
    const detail = await Promise.race([
      fn(),
      new Promise((_resolve, reject) => {
        timer = setTimeout(() => reject(new Error(`timed out after ${timeoutMs} ms`)), timeoutMs);
      }),
    ]);
    checks.push({ name, ok: true, detail: detail ?? '' });
  } catch (error) {
    const message = String(error?.message ?? error)
      .replace(/\s+/g, ' ')
      .trim();
    checks.push({ name, ok: false, detail: message.slice(0, 2000) });
    await recoverFromFailure();

    clearTimeout(timer);
  }
  const entry = checks.at(-1);
  console.log(
    `  ${entry.ok ? 'PASS' : 'FAIL'}  ${name} — ${entry.detail} (${((Date.now() - started) / 1000).toFixed(1)}s)`,
  );
}

/**
 * Open a command through the palette, by a label pattern (`Ctrl+K` then Enter is the
 * palette's own keyboard path — the one a user takes, and the one that does not depend on
 * the item markup).
 */
async function openPalette(pattern) {
  await page.keyboard.press('Control+K');
  await page.waitForTimeout(500);
  await page.keyboard.type(pattern.split('|')[0]);
  await page.waitForTimeout(700);
  const option = page.getByRole('option', { name: new RegExp(pattern, 'i') }).first();
  const names = await page.getByRole('option').allInnerTexts();
  if ((await option.count()) === 0) {
    throw new Error(`no palette entry matches /${pattern}/ — entries: ${JSON.stringify(names)}`);
  }
  await option.click();
  await page.waitForTimeout(1200);
  // The palette's own input, not "any listbox": a dock panel's select is a listbox too, and
  // the first version of this guard failed on those instead of on the palette.
  const input = page.locator('input[aria-label="Komut paleti"], input[placeholder*="Komut"]');
  if ((await input.count()) > 0) throw new Error(`the palette is still open after /${pattern}/`);
}

/** Export the current version through File → Dışa aktar and save the download. */
async function exportViaMenu(target) {
  const download = page.waitForEvent('download', { timeout: 120_000 });
  await runMenuCommand('Dosya', 'Dışa aktar');
  const saved = await download;
  await saved.saveAs(target);
}

/**
 * Is the port free? Asked before this harness spawns its own server, because a **stale**
 * server answers the readiness probe below while the spawned child dies on `EADDRINUSE` —
 * the checks would then report on bytes this run never produced, which is a green run over
 * the wrong `dist/`. The wait covers the one honest case where the port still answers: a
 * run that ended a moment ago and whose listener has not finished closing.
 */
async function waitForFreePort(url, timeoutMs = 2_000) {
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    const served = await fetch(url, { signal: AbortSignal.timeout(1_000) }).then(
      (response) => response.ok,
      () => false,
    );
    if (!served) return;
    if (Date.now() > deadline) {
      throw new Error(
        `${url} still answers — another server holds port ${port}: stop it, pass --port <other>, ` +
          'or set VERIFY_ORIGIN to that origin to target it deliberately',
      );
    }
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}

/**
 * Wait for the harness's own preview server.
 *
 * `child` is what keeps a stale server from standing in for this run's evidence: a leaked
 * `preview-dist` on the port answers every probe below, so without the liveness checks the
 * child could die on `EADDRINUSE` and the checks would still run — against bytes the
 * harness never spawned, which is a green run over the wrong `dist/`.
 */
async function waitForServer(url, child = null, timeoutMs = 20_000) {
  const died = (code) =>
    new Error(
      `the harness's own preview server exited (code ${code}) before ${url} answered — ` +
        `port ${port} is probably taken by another server; its output: ${serverLog.trim() === '' ? '(none)' : serverLog.trim()}`,
    );
  const deadline = Date.now() + timeoutMs;
  for (;;) {
    if (child !== null && child.exitCode !== null) throw died(child.exitCode);
    const served = await fetch(url).then(
      (response) => response.ok,
      () => false,
    );
    if (served) {
      // `EADDRINUSE` is reported asynchronously, so a stale server's first answer can beat
      // the child's own death by a few milliseconds: the survivor check runs after it.
      await new Promise((resolve) => setTimeout(resolve, 500));
      if (child !== null && child.exitCode !== null) throw died(child.exitCode);
      return;
    }
    if (Date.now() > deadline) throw new Error(`no answer from ${url} within ${timeoutMs} ms`);
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
}

/** A menu command by a label *pattern*, so a wording change reports itself instead of hanging. */
async function runMenuCommand(menu, pattern) {
  const bar = page.getByRole('menubar');
  await bar.getByRole('menuitem', { name: menu, exact: true }).first().click();
  const menuPanel = page.getByRole('menu');
  await menuPanel.waitFor({ state: 'visible', timeout: 10_000 });
  const matcher = new RegExp(pattern, 'i');
  const names = await menuPanel.getByRole('menuitem').allInnerTexts();
  const item = menuPanel
    .getByRole('menuitem', { name: matcher })
    .or(menuPanel.getByRole('menuitemcheckbox', { name: matcher }))
    .first();
  if ((await item.count()) === 0) {
    throw new Error(`no menu entry matches /${pattern}/ — entries: ${JSON.stringify(names)}`);
  }
  await item.click();
  await page.waitForTimeout(400);
}

async function openFixture(path) {
  await page.setInputFiles('input[type="file"]', path);
  await page.waitForSelector('.pdfViewer .page', { timeout: 60_000 });
  await page.waitForFunction(
    (expected) => (document.querySelector('footer')?.textContent ?? '').includes(`/ ${expected}`),
    FIXTURE_PAGES,
    { timeout: 60_000 },
  );
}

const fixture = await buildFixture();
let server = null;
let browser = null;
try {
  if (!externalServer) {
    // `preview-dist` installs no error handler on `listen`, so on a taken port it dies with
    // `EADDRINUSE` while whatever already holds the port keeps answering — and the checks
    // would run against that process. Refuse before spawning; `VERIFY_ORIGIN` stays the way
    // to target a server on purpose.
    await waitForFreePort(`${origin}/editor/`);
    server = spawn(
      process.execPath,
      [join(ROOT, 'tools', 'preview-dist.mjs'), '--root', 'dist', '--port', String(port)],
      { cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe'] },
    );
    const capture = (chunk) => {
      serverLog = `${serverLog}${String(chunk)}`.slice(-1500);
    };
    server.stdout.on('data', capture);
    server.stderr.on('data', capture);
    await waitForServer(`${origin}/editor/`, server);
  }

  const executablePath = process.env.CHROMIUM_PATH ?? chromium.executablePath();
  try {
    browser = await chromium.launch(
      existsSync(executablePath) ? { executablePath, headless: true } : { headless: true },
    );
  } catch (error) {
    if (String(error?.message ?? '').includes("Executable doesn't exist")) {
      // Not a skip: this driver *is* the browser evidence, and exiting zero without one
      // would report an acceptance run that never happened. Throwing lets `finally` still
      // remove the fixture and stop the spawned server, and the process exits non-zero.
      throw new Error(
        `phase4-check: no Chromium to drive (looked for ${executablePath}).\n` +
          '  Install it:  pnpm exec playwright install chromium\n' +
          '  Or point CHROMIUM_PATH at an existing Chromium/Chrome executable.',
      );
    }
    throw error;
  }
  const context = await browser.newContext({
    viewport: { width: 1600, height: 1100 },
    acceptDownloads: true,
    // Every label the checks look up is Turkish. The app picks its language from
    // `navigator.language` when nothing is stored (`LanguageSelector.tsx`), so without this
    // pin the run's labels depend on the host's system language — an `en-*` host renders
    // English and fails the lookups for the wrong reason.
    locale: 'tr-TR',
  });
  page = await context.newPage();
  page.on('pageerror', (error) => consoleErrors.push(`pageerror: ${error.message.slice(0, 200)}`));
  page.on('console', (message) => {
    if (message.type() !== 'error') return;
    const text = message.text();
    // pdf.js's fontkit noise about the pinned Noto Sans (`FT_Load_Glyph … invalid
    // outline`) arrives through console.error and was measured in the previous
    // session as engine noise with no observable consequence. Kept out of the page
    // error count so the count stays a signal.
    if (/FT_Load_Glyph|invalid composite glyph/.test(text)) return;
    consoleErrors.push(`console: ${text.slice(0, 200)}`);
  });

  await check('shell renders under the production policy', async () => {
    await page.goto(`${origin}/editor/`, { waitUntil: 'load' });
    await page.waitForSelector('input[type="file"]', { state: 'attached', timeout: 30_000 });
    await page.waitForSelector('footer', { timeout: 30_000 });
    const isolated = await page.evaluate(() => globalThis.crossOriginIsolated === true);
    if (!isolated) throw new Error('crossOriginIsolated is false: COOP/COEP are not in force');
    return 'shell painted, crossOriginIsolated true';
  });

  await check(`open: the fixture shows ${FIXTURE_PAGES} pages`, async () => {
    await openFixture(fixture);
    return `${FIXTURE_PAGES} pages`;
  });

  await check('text model: the text tool paints one overlay per block on page 1', async () => {
    await runMenuCommand('Araçlar', '^Metni düzenle$');
    await page.waitForSelector('[data-text-block]', { timeout: 60_000 });
    const blocks = await page.evaluate(() =>
      [...document.querySelectorAll('[data-text-block]')].map((node) => ({
        id: node.getAttribute('data-text-block'),
        editability: node.getAttribute('data-editability'),
        title: node.getAttribute('aria-label') ?? node.getAttribute('title') ?? '',
      })),
    );
    if (blocks.length === 0) throw new Error('no block overlay was painted');
    return `${blocks.length} block(s): ${blocks.map((block) => `${block.id}/${block.editability}`).join(', ')}`;
  });

  await check('text edit: selecting the paragraph opens the editor with its own text', async () => {
    const target = await page.evaluate((sentinel) => {
      const nodes = [...document.querySelectorAll('[data-text-block]')];
      // The block's own text, not the aria-label: the label is clipped for the
      // accessibility name, and a paragraph's sentinel can sit past the clip.
      const node = nodes.find((candidate) =>
        (candidate.getAttribute('data-block-text') ?? '').includes(sentinel),
      );
      if (node === undefined) return null;
      node.dispatchEvent(new MouseEvent('click', { bubbles: true, button: 0 }));
      return node.getAttribute('data-text-block');
    }, SENTINEL);
    if (target === null) {
      const texts = await page.evaluate(() =>
        [...document.querySelectorAll('[data-text-block]')].map((node) =>
          (node.getAttribute('data-block-text') ?? '').slice(0, 60),
        ),
      );
      throw new Error(`no block carries the sentinel — blocks: ${JSON.stringify(texts)}`);
    }
    // Every operation opens in the tools panel as a region named by its title.
    const form = page.getByRole('region', { name: 'Metni düzenle' });
    await form.waitFor({ state: 'visible', timeout: 30_000 });
    const prefilled = await form.locator('textarea').first().inputValue();
    if (!prefilled.includes('KADIKÖY')) {
      throw new Error(`the editor did not prefill the block text: "${prefilled.slice(0, 120)}"`);
    }
    return `block ${target} selected, ${prefilled.length} characters prefilled`;
  });

  await check('text edit: replacing the paragraph produces a new version', async () => {
    const form = page.getByRole('region', { name: 'Metni düzenle' });
    const area = form.locator('textarea').first();
    await area.fill(
      `${REPLACEMENT} şubesi bu kuralı istisnasız uygular ve arşivini yerel tutar. Metin düzenleme kabul ölçütü.`,
    );
    // Step one runs the edit and shows its report ("Önizle"); step two applies it.
    await form.getByRole('button', { name: 'Önizle', exact: true }).click();
    // The dialog either offers the document action (the run produced bytes) or shows
    // the dictionary sentence plus the engine's own diagnostic. Waiting on the report
    // action alone would report both outcomes as "timed out", which says nothing.
    await page.waitForFunction(
      () =>
        /Belgeye uygula/.test(document.body.innerText) ||
        document.querySelector('[data-dialog-diagnostic]') !== null,
      undefined,
      { timeout: 180_000 },
    );
    const failure = await page.evaluate(
      () =>
        document.querySelector('[data-dialog-diagnostic]')?.getAttribute('data-dialog-diagnostic') ?? null,
    );
    if (failure !== null) throw new Error(`the operation failed its own verification: ${failure}`);
    const apply = page.getByRole('button', { name: 'Belgeye uygula' }).first();
    if ((await apply.count()) > 0) await apply.click();
    await page.waitForTimeout(2500);
    const pages = await page.evaluate(() => document.querySelector('footer')?.textContent ?? '');
    if (!pages.includes(`/ ${FIXTURE_PAGES}`)) {
      throw new Error(`page count moved after the edit: ${pages}`);
    }
    return 'the edit ran, its report offered the document action, page count held';
  });

  await check('text edit: the new text is searchable in the app', async () => {
    await page.keyboard.press('Control+f');
    const field = page.locator('search input[type="text"]').first();
    await field.waitFor({ state: 'visible', timeout: 10_000 });
    await field.fill(REPLACEMENT);
    await field.press('Enter');
    await page.waitForFunction(
      () => /eşleşme|bulunamadı/i.test(document.querySelector('search')?.textContent ?? ''),
      undefined,
      { timeout: 30_000 },
    );
    const label = await page.evaluate(
      () => document.querySelector('search')?.textContent?.replace(/\s+/g, ' ').trim() ?? '',
    );
    if (!/\d+\s*\/\s*\d+/.test(label)) throw new Error(`no match reported: ${label}`);
    await page.keyboard.press('Escape');
    return label;
  });

  await check('text edit: the exported file lost the targeted occurrence only', async () => {
    const download = page.waitForEvent('download', { timeout: 180_000 });
    await page.getByRole('menubar').getByRole('menuitem', { name: 'Dosya', exact: true }).first().click();
    const fileMenu = page.getByRole('menu');
    await fileMenu.waitFor({ state: 'visible', timeout: 10_000 });
    await fileMenu.getByText('Dışa aktar', { exact: false }).first().click();
    const file = await download;
    const saved = join(fixtureDir, 'edited.pdf');
    await file.saveAs(saved);

    const texts = await pageTexts(saved);
    const joined = texts.join('\n');
    const sentinelCount = (joined.match(new RegExp(SENTINEL, 'g')) ?? []).length;
    const replacementCount = (joined.match(new RegExp(REPLACEMENT, 'g')) ?? []).length;
    const pageCount = readFixture(mupdf, readFileSync(saved)).pageCount;

    if (pageCount !== FIXTURE_PAGES) throw new Error(`page count ${pageCount} in the saved file`);
    if (replacementCount === 0)
      throw new Error(`the replacement is not in the saved file: ${joined.slice(0, 200)}`);
    if (sentinelCount !== 1) {
      throw new Error(
        `the sentinel appears ${sentinelCount} time(s); the untouched page-2 copy must be the only one`,
      );
    }
    if (!texts[0]?.includes(REPLACEMENT)) throw new Error(`page 1 reads "${texts[0]?.slice(0, 160)}"`);
    return `${pageCount} pages; "${REPLACEMENT}" ×${replacementCount}; "${SENTINEL}" ×${sentinelCount} (page 2 only)`;
  });

  await check('structure: the exported file kept its link and its outline', async () => {
    const saved = join(fixtureDir, 'edited.pdf');
    const reopened = readFixture(mupdf, readFileSync(saved));
    const subtypes = reopened.annotations(3).map((annotation) => annotation.subtype);
    if (!subtypes.includes('Link')) throw new Error(`page 4 has no link annotation: ${subtypes.join(', ')}`);
    const titles = reopened.outlineTitles();
    if (titles.length === 0) throw new Error('the outline is gone from the saved file');
    if (titles.length !== 2) throw new Error(`outline entries: ${JSON.stringify(titles)}`);
    return `link kept on page 4, outline entries ${JSON.stringify(titles)}`;
  });

  await check(
    'visual: page 2 text is unchanged after the edit (a text comparison, not a pixel one)',
    async () => {
      const saved = join(fixtureDir, 'edited.pdf');
      const [before, after] = await Promise.all([pageTexts(fixture), pageTexts(saved)]);
      // Two failed reads would be "equal" too: the page must have been read, and had text.
      if (before.length !== after.length || !before[1]) {
        throw new Error(`page 2 was not read from both files (${before.length} vs ${after.length} pages)`);
      }
      if (before[1] !== after[1]) {
        throw new Error(`page 2 changed: "${before[1]}" → "${after[1]}"`);
      }
      return `page 2 text identical before and after (${before[1].length} characters)`;
    },
  );
  /**
   * The features added after the text engine (measurement, comparison,
   * accessibility, batch). Each drives the app's own route — the palette or a menu — and
   * asserts the produced artefact, exactly like the checks above. Signing has its own
   * driver (`sign-check.mts`), because its acceptance is a cryptographic verdict
   * rather than a surface assertion.
   *
   * They also share one prerequisite, and this check is it: **simple mode is the default**
   * (`apps/web/src/interface-mode.ts`), and there the palette and the menus offer only
   * `SIMPLE_MODE_COMMANDS`, while all four of these commands — measure, compare,
   * accessibility, batch — are advanced. A run that never leaves the simple mode searches a
   * UI that deliberately does not offer them, which is what the four failures before this
   * check looked like. The way out is the user's own: the settings dialog's mode choice
   * (`SettingsDialog.tsx`), which the shell stores and announces on `pdf-mode-change` so
   * every surface re-filters. Seeding the storage key instead would
   * test a state the interface cannot reach; flipping the app's default would hide the
   * filter from the harness rather than exercise it.
   */
  await check('prerequisite: the settings leave the simple mode for the advanced one', async () => {
    // Shell-side evidence, not the switch's own state: the switch would flip its label even
    // if nothing listened. The dock's structure tabs exist only in advanced mode
    // (`SIMPLE_MODE_DOCK_TABS`), so their absence proves the documented simple default and
    // their arrival proves the shell re-filtered.
    const dock = page.getByRole('tablist', { name: 'Sol panel' }).getByRole('tab');
    const structureTab = page.getByRole('tab', { name: 'Katmanlar' });
    if ((await structureTab.count()) > 0) {
      throw new Error(
        'the shell already offers the advanced structure tabs — this check assumes the documented simple default',
      );
    }
    const before = await dock.count();
    if (before === 0) {
      throw new Error('no left-dock tab strip is rendered — this check reads the mode from it');
    }
    await page.getByRole('button', { name: 'Ayarlar', exact: true }).first().click();
    const settings = page.getByRole('dialog', { name: 'Ayarlar' });
    await settings.waitFor({ state: 'visible', timeout: 15_000 });
    if (await settings.getByRole('radio', { name: 'Gelişmiş mod' }).isChecked()) {
      throw new Error('the settings report advanced mode while the shell still hides the advanced tabs');
    }
    await settings.getByRole('radio', { name: 'Gelişmiş mod' }).check();
    await settings.getByRole('button', { name: 'Kapat', exact: true }).click();
    await structureTab.first().waitFor({ state: 'visible', timeout: 15_000 });
    const after = await dock.count();
    if (after <= before) {
      throw new Error(`the document dock offers ${after} tab(s) after the switch and ${before} before it`);
    }
    return `simple by default (${before} dock tabs, the structure tabs hidden) → advanced (${after} dock tabs)`;
  });

  await check('measure: the ruler writes a /Measure annotation into the exported file', async () => {
    await openPalette('Mesafe|Ölçüm');
    const sheet = await page.locator('.pdfViewer .page').first().boundingBox();
    if (sheet === null) throw new Error('no page to measure on');
    // Two clicks: a distance needs a start and an end. The layer's own gesture, no dialog.
    await page.mouse.click(sheet.x + 120, sheet.y + 200);
    await page.waitForTimeout(200);
    await page.mouse.click(sheet.x + 320, sheet.y + 260);
    await page.waitForTimeout(400);
    // The gesture's own ending: the ruler finishes on Enter (or a double click), which is
    // the tool's documented interaction, not a second click.
    await page.keyboard.press('Enter');
    await page.waitForTimeout(600);
    // Two Escape presses end the tool: one clears the chain, the second disarms it — and the
    // overlay has to be gone before the export menu is reachable (it is not, otherwise: that
    // is the defect this check found).
    await page.keyboard.press('Escape');
    await page.keyboard.press('Escape');
    await page.waitForTimeout(400);
    const readout = await page
      .locator('[data-testid="measure-readout"], [aria-label*="Ölçüm"], fieldset')
      .first()
      .innerText()
      .catch(() => '');
    await exportViaMenu(join(fixtureDir, 'measured.pdf'));
    const written = readFixture(mupdf, readFileSync(join(fixtureDir, 'measured.pdf')));
    const measured = written.annotations(0).filter((annotation) => annotation.hasMeasure).length;
    if (measured === 0) throw new Error(`no /Measure annotation in the exported file (readout "${readout}")`);
    return `${measured} measure annotation(s) with a /Measure dictionary`;
  });

  await check(
    'compare: the panel reports the document against its own export as unchanged on every page',
    async () => {
      await openPalette('Karşılaştırma');
      // The panel's own controls, by their dictionary labels: the file input is a hidden
      // element behind a button, and Playwright can set a hidden input directly.
      const pick = page.getByRole('button', { name: /İkinci belgeyi seç/i }).first();
      await pick.waitFor({ state: 'visible', timeout: 15_000 });
      // The user's own path: the button opens the file chooser, and the chooser is answered
      // here. Setting a hidden input directly picked another input in the shell.
      const [chooser] = await Promise.all([
        page.waitForEvent('filechooser', { timeout: 15_000 }),
        pick.click(),
      ]);
      // The app's document has been edited since the fixture was written (page 1 carries the
      // replacement), so "itself" is the file the previous check exported from the document as it is now.
      await chooser.setFiles(join(fixtureDir, 'measured.pdf'));
      await page.waitForTimeout(900);
      const run = page.getByRole('button', { name: /Metni karşılaştır/i }).first();
      if (await run.isDisabled()) throw new Error('the text run is disabled after picking a document');
      await run.click();
      // The comparison's own rows, one per page (`data-compare-row` in ComparePanel): the
      // table is the result, so nothing else on the page can satisfy this.
      const rows = page.locator('[data-compare-row^="text:"]');
      await rows.first().waitFor({ state: 'visible', timeout: 30_000 });
      const found = await rows.count();
      if (found !== FIXTURE_PAGES) {
        throw new Error(`the comparison has ${found} page row(s), the fixture has ${FIXTURE_PAGES}`);
      }
      for (let at = 0; at < found; at += 1) {
        const row = rows.nth(at);
        const label = await row.getAttribute('data-compare-row');
        const cells = await row.locator('td').allInnerTexts();
        // Cells: method, status, detail, jump. A page that changed says "Değişti" and counts lines.
        if (cells[1]?.trim() !== 'Aynı' || !cells[2]?.includes('Değişiklik yok')) {
          throw new Error(`${label} is not reported as unchanged: ${JSON.stringify(cells)}`);
        }
      }
      // The two documents are the same file, so the page counts agree and no mismatch is named.
      const results = await page.locator('body').innerText();
      if (
        !results.includes(`Sayfa sayısı: ${FIXTURE_PAGES} → ${FIXTURE_PAGES}`) ||
        results.includes('Sayfa sayısı farkı')
      ) {
        throw new Error('the page counts of the two documents do not agree in the report');
      }
      return `all ${found} page rows report "Aynı" / "Değişiklik yok" against the same file`;
    },
  );

  await check('accessibility: the check names the missing structure on an untagged file', async () => {
    await openPalette('Erişilebilirlik');
    const checkButton = page.getByRole('button', { name: /^Denetle$/i }).first();
    await checkButton.waitFor({ state: 'visible', timeout: 15_000 });
    await checkButton.click();
    // The check reads the whole document: wait for the report's own rows, not for a fixed time.
    // The rule under test is the structure tree's (`op.a11y.check.structTree`): on an untagged
    // file its finding is the exact sentence below, listed under "Bulunan sorunlar".
    const row = page.locator('li').filter({ hasText: /^Yapı ağacı \(\/StructTreeRoot\) yok\.$/ });
    await row.first().waitFor({ state: 'visible', timeout: 60_000 });
    if ((await row.count()) !== 1)
      throw new Error(`the structure-tree finding is listed ${await row.count()} times`);
    const group = await row.first().locator('xpath=ancestor::section[1]/h4').innerText();
    if (group.trim() !== 'Bulunan sorunlar') {
      throw new Error(
        `the missing structure tree is reported under "${group.trim()}", not as a found problem`,
      );
    }
    // The positive form of the same rule must be absent: a tree that was found says so differently.
    if ((await page.getByText(/^Yapı ağacı var \(/).count()) !== 0) {
      throw new Error('the report claims a structure tree while also reporting it missing');
    }
    const summary = await page.getByText(/^\d+ sayfa · \d+ bulgu · \d+ bilinmiyor$/).innerText();
    if (!summary.includes(`${FIXTURE_PAGES} sayfa`))
      throw new Error(`the report summary names another page count: ${summary}`);
    return `structure tree reported missing under "${group.trim()}" (${summary})`;
  });

  await check('batch: a run over one file reports it and produces a download', async () => {
    await runMenuCommand('Dosya', 'Toplu');
    const dialog = page
      .locator('[role="dialog"]')
      .filter({ hasText: /Toplu işlem/ })
      .first();
    await dialog.waitFor({ state: 'visible', timeout: 15_000 });
    await dialog.locator('input[type="file"]').first().setInputFiles(fixture);
    await page.waitForTimeout(400);
    // Tick one real step — the first checkbox may be the whole-step switch — then run.
    const boxes = dialog.getByRole('checkbox');
    const count = await boxes.count();
    if (count === 0) throw new Error('the dialog offers no steps to tick');
    await boxes.nth(count > 1 ? 1 : 0).check();
    await page.waitForTimeout(300);
    const runButton = dialog.getByRole('button', { name: /Çalıştır/i }).first();
    if (await runButton.isDisabled()) {
      throw new Error(`run is disabled after ticking a step (checkboxes: ${count})`);
    }
    await runButton.click();
    await page.waitForTimeout(6000);
    // The report region, not the dialog's own intro: the intro sentence mentions the word
    // "başarısız" too, and a check that matches it would pass without a run ever happening.
    const text = await dialog.innerText();
    const after = text.slice(text.indexOf('Dosya raporu'));
    if (after.length < 10 || !/bayt/i.test(after)) {
      throw new Error(`no per-file report appeared: ${text.replace(/\s+/g, ' ').slice(0, 240)}`);
    }
    return after.replace(/\s+/g, ' ').slice(0, 160);
  });
} finally {
  const failed = checks.filter((entry) => !entry.ok);
  console.log('');
  console.log(
    `  ${checks.length - failed.length} passed, ${failed.length} failed, ${consoleErrors.length} page errors`,
  );
  if (consoleErrors.length > 0) {
    console.log('  page errors:');
    for (const error of consoleErrors.slice(0, 10)) console.log(`    - ${error}`);
  }
  if (failed.length > 0) {
    console.log('  failures:');
    for (const entry of failed) console.log(`    - ${entry.name}: ${entry.detail}`);
  }
  if (!keepFixture) rmSync(fixtureDir, { recursive: true, force: true });
  else console.log(`  fixture kept at ${fixtureDir}`);
  if (browser !== null) await browser.close();
  if (server !== null) {
    server.kill();
    server.stdout.destroy();
    server.stderr.destroy();
  }
}
process.exit(checks.some((entry) => !entry.ok) ? 1 : 0);
