/**
 * The signing writer, end to end (`ops/sign.ts`, `signature-cms.ts`, `signature-pkcs12.ts`).
 *
 * The identity comes from **OpenSSL**, not from this repository: a self-signed certificate,
 * its key and a PKCS#12 container are generated by a second implementation, imported through
 * the product's own `importPkcs12`, and used to sign a PDF. The produced file is then read
 * back with the **product's own verifier** — the one the properties panel calls — so the loop
 * closes inside the product: a signature nobody can verify is worth nothing.
 *
 * The tamper case is what makes the others mean something: **one byte changed after signing**
 * has to break the verdict. A writer whose output is "valid" no matter what is not a
 * signature.
 *
 * Usage: npx tsx tools/spikes/sign-check.mts
 */

import { spawnSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { signPdf } from '../../packages/pdf-core/src/ops/sign';
import { verifySignatures } from '../../packages/pdf-core/src/ops/signature-status';
import { describeCertificate, importPkcs12 } from '../../packages/pdf-core/src/signature-pkcs12';
// @ts-expect-error — a plain ESM helper without typings, used by this script only.
import { installMupdfHook } from './node-mupdf-hook.mjs';

// The product loads MuPDF by its served URL; outside a browser that URL resolves to the
// same pinned package (`node-mupdf-hook.mjs`).
installMupdfHook();
const mupdf = (await import(
  pathToFileURL(
    createRequire(new URL('../../packages/pdf-core/package.json', import.meta.url)).resolve('mupdf'),
  ).href
)) as typeof import('mupdf');

/** The first signature widget of page 1: its field type, appearance, range and CMS. */
function signatureOf(bytes: Uint8Array) {
  const doc = mupdf.PDFDocument.openDocument(bytes.slice(), 'application/pdf').asPDF();
  if (doc === null) throw new Error('not a PDF');
  try {
    const annots = doc.findPage(0).get('Annots').resolve();
    for (let index = 0; index < annots.length; index += 1) {
      const dict = annots.get(index).resolve();
      if (dict.get('FT').isNull() || dict.get('FT').asName() !== 'Sig') continue;
      const value = dict.get('V').resolve();
      const range = value.get('ByteRange').resolve();
      return {
        hasAppearance: !dict.get('AP').isNull(),
        range: Array.from({ length: range.length }, (_unused, at) => range.get(at).asNumber()),
        contents: new Uint8Array(value.get('Contents').asByteString()),
      };
    }
    return null;
  } finally {
    doc.destroy();
  }
}

/** An offset inside the signed range that is a digit of the page's `/MediaBox`. */
function mediaBoxDigit(bytes: Uint8Array): number {
  const text = Buffer.from(bytes).toString('latin1');
  const at = text.indexOf('/MediaBox');
  const digit = text.slice(at).search(/[1-9]/);
  if (at < 0 || digit < 0) throw new Error('no /MediaBox digit in the produced bytes');
  return at + digit;
}

const dir = join(tmpdir(), `pdf-editor-sign-${process.pid}`);
mkdirSync(dir, { recursive: true });
const context = { signal: new AbortController().signal, onProgress: () => {} };

const checks: { name: string; ok: boolean; detail: string }[] = [];
async function check(name: string, fn: () => Promise<string>) {
  try {
    checks.push({ name, ok: true, detail: await fn() });
  } catch (error) {
    checks.push({ name, ok: false, detail: String((error as Error)?.message ?? error).slice(0, 500) });
  }
  const entry = checks.at(-1);
  console.log(`  ${entry.ok ? 'PASS' : 'FAIL'}  ${name} — ${entry.detail}`);
}

/** A key, a self-signed certificate and a PKCS#12 container, all from OpenSSL. */
function generateIdentity(): void {
  const run = (args: string[], stdin?: string): void => {
    const result = spawnSync('openssl', args, { cwd: dir, encoding: 'utf8', input: stdin });
    if (result.status !== 0) {
      throw new Error(`openssl ${args[0]} failed: ${(result.stderr ?? '').slice(0, 300)}`);
    }
  };
  run([
    'req',
    '-x509',
    '-newkey',
    'rsa:2048',
    '-keyout',
    'key.pem',
    '-out',
    'cert.pem',
    '-days',
    '3',
    '-nodes',
    '-subj',
    '/CN=PDF Editor Signing Test/O=Probe/C=TR',
    '-addext',
    'keyUsage=digitalSignature',
    '-addext',
    'extendedKeyUsage=emailProtection',
  ]);
  run([
    'pkcs12',
    '-export',
    '-out',
    'identity.p12',
    '-inkey',
    'key.pem',
    '-in',
    'cert.pem',
    '-passout',
    'pass:testpass',
  ]);
}

generateIdentity();

const identity = await importPkcs12(new Uint8Array(readFileSync(join(dir, 'identity.p12'))), 'testpass');

{
  const doc = new mupdf.PDFDocument();
  const font = doc.addObject({ Type: 'Font', Subtype: 'Type1', BaseFont: 'Helvetica' });
  doc.insertPage(
    0,
    doc.addPage(
      [0, 0, 400, 300],
      0,
      { Font: { F: font } },
      'BT /F 14 Tf 40 260 Td (Signature fixture) Tj ET',
    ),
  );
  writeFileSync(join(dir, 'unsigned.pdf'), doc.saveToBuffer('').asUint8Array());
  doc.destroy();
}
const unsigned = new Uint8Array(readFileSync(join(dir, 'unsigned.pdf')));
let signed = new Uint8Array();

/** A fresh copy of the unsigned fixture: a producer may transfer the buffer it is given. */
async function fixture(): Promise<Uint8Array> {
  return new Uint8Array(readFileSync(join(dir, 'unsigned.pdf')));
}

await check('import: the OpenSSL container yields the certificate and a usable key', async () => {
  const described = describeCertificate(identity.certificate);
  if (identity.commonName !== 'PDF Editor Signing Test')
    throw new Error(`CN reads "${String(identity.commonName)}"`);
  if (described.issuer !== 'PDF Editor Signing Test')
    throw new Error(`issuer reads "${String(described.issuer)}"`);
  if (identity.privateKey.algorithm.name !== 'RSASSA-PKCS1-v1_5') {
    throw new Error(`key algorithm is ${identity.privateKey.algorithm.name}`);
  }
  return `CN "${identity.commonName}", ${identity.certificate.byteLength} B certificate, key ${identity.privateKey.algorithm.name}`;
});

await check('sign: the field is created, the CMS written and the range stated', async () => {
  const outcome = await signPdf(
    unsigned,
    {
      identity,
      field: { name: 'Imza1' },
      reason: 'Kabul testi',
      location: 'Ankara',
      signerName: String(identity.commonName),
      date: new Date('2026-09-16T12:00:00Z'),
    },
    context,
  );
  signed = new Uint8Array(outcome.bytes);
  writeFileSync(join(dir, 'signed.pdf'), signed);
  const notes = outcome.report.notes.map((entry) => entry.key).join(', ');
  if (!notes.includes('op.note.sign.signed')) throw new Error(`notes: ${notes}`);
  if (outcome.report.incremental !== false)
    throw new Error('a signed file claimed the incremental fast path');
  const signature = signatureOf(signed);
  if (signature === null) throw new Error('no /Sig field on page 1');
  if (signature.contents.every((byte) => byte === 0)) throw new Error('the /Contents entry looks empty');
  return `field Imza1, [${signature.range.join(' ')}], ${signed.byteLength} B file, notes: ${notes.slice(0, 90)}`;
});

await check('verify: the product’s own verifier reports the signature valid', async () => {
  const verdicts = await verifySignatures(signed);
  if (verdicts.length !== 1) throw new Error(`${verdicts.length} signature(s) found`);
  const [verdict] = verdicts;
  if (verdict.integrity !== 'valid')
    throw new Error(`integrity is "${verdict.integrity}" (${verdict.reasonKey})`);
  if (verdict.subFilter !== 'ETSI.CAdES.detached') throw new Error(`/SubFilter is ${verdict.subFilter}`);
  if (verdict.signer !== 'PDF Editor Signing Test')
    throw new Error(`signer reads "${String(verdict.signer)}"`);
  if (verdict.coverage !== 'covers-whole-document') throw new Error(`coverage is ${verdict.coverage}`);
  // A self-signed certificate is *read* as self-signed, and trust is never claimed: this
  // build has no trust store and no network.
  if (verdict.trust !== 'self-signed')
    throw new Error(`a self-signed certificate must read self-signed, got "${verdict.trust}"`);
  if (verdict.changesAfterSigning !== 0)
    throw new Error(`${verdict.changesAfterSigning} change(s) after signing`);
  // The name and the date are read from the *file's* own strings: writing them as PDF names
  // is a defect this check missed once, and the two assertions are what would have caught it.
  if (verdict.fieldName !== 'Imza1') throw new Error(`field name reads "${verdict.fieldName}"`);
  if (verdict.signedAt === null || !verdict.signedAt.startsWith('2026-09-16T')) {
    throw new Error(`/M reads as "${String(verdict.signedAt)}"`);
  }
  return `integrity ${verdict.integrity}, trust ${verdict.trust}, coverage ${verdict.coverage}, signer "${String(verdict.signer)}", signedAt ${String(verdict.signedAt)}`;
});

await check('tamper: one byte changed after signing fails the signature', async () => {
  const tampered = new Uint8Array(signed);
  // Inside the signed range: a digit of the page's /MediaBox, so the file still parses
  // and a reader still opens it — only the signature notices.
  const at = mediaBoxDigit(tampered);
  tampered[at] = tampered[at] === 0x39 ? 0x38 : (tampered[at] ?? 0x30) + 1;
  const [verdict] = await verifySignatures(tampered);
  if (verdict === undefined) throw new Error('the tampered file carries no signature');
  if (verdict.integrity === 'valid') throw new Error('the tampered file still reports a valid signature');
  return `integrity ${verdict.integrity} after flipping byte ${at}`;
});

await check('visible: a signature with a stamp still verifies, and the stamp is there', async () => {
  const outcome = await signPdf(
    unsigned,
    {
      identity,
      field: {
        name: 'Imza2',
        rect: { x: 40, y: 40, width: 240, height: 70 },
        lines: [String(identity.commonName), '2026-09-16'],
      },
      signerName: String(identity.commonName),
      date: new Date('2026-09-16T12:00:00Z'),
    },
    context,
  );
  writeFileSync(join(dir, 'signed-visible.pdf'), outcome.bytes);
  const signature = signatureOf(outcome.bytes);
  if (signature === null) throw new Error('no signature widget after the visible sign');
  if (!signature.hasAppearance) throw new Error('the visible field carries no /AP');
  const verdicts = await verifySignatures(outcome.bytes);
  if (verdicts[0]?.integrity !== 'valid')
    throw new Error(`visible signature integrity: ${String(verdicts[0]?.integrity)}`);
  return `stamped field verifies (${outcome.bytes.byteLength} B)`;
});

await check('forged: a rewritten messageDigest is caught by the signature itself', async () => {
  /**
   * The attack the digest-only check could not see: change a byte the signature covers *and*
   * rewrite the `messageDigest` attribute to match it. The blob the digest lives in is the
   * blob being edited, so the attribute is trivially repairable — only the signature value,
   * verified with the certificate's public key, notices.
   */
  const tampered = signed.slice();
  // A byte inside the covered range, a digit of the page's /MediaBox: harmless to the
  // PDF's structure, fatal to the signature.
  const at = mediaBoxDigit(tampered);
  tampered[at] = tampered[at] === 0x39 ? 0x38 : (tampered[at] ?? 0x30) + 1;

  const view = signatureOf(tampered);
  if (view === null) throw new Error('the tampered file carries no signature');
  const range = view.range;

  // Four numbers, read once: a `!` here would hide a signature dictionary that carried
  // something other than four integers, which is exactly what this check is about.
  const [start1, length1, start2, length2] = range;
  if (start1 === undefined || length1 === undefined || start2 === undefined || length2 === undefined) {
    throw new Error('the ByteRange did not come back as four numbers');
  }
  const covered = () =>
    Buffer.concat([
      Buffer.from(tampered.subarray(start1, start1 + length1)),
      Buffer.from(tampered.subarray(start2, start2 + length2)),
    ]);
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', covered()));
  const forged = Buffer.from(digest).toString('hex').toUpperCase();

  // The `/Contents` value is a **hex string**, so the attribute's octets are in the file as
  // ASCII hex — the patch has to happen in that form, same length, every offset preserved.
  const oldDigest = view.contents;
  const attribute = new Uint8Array(32);
  const marker = oldDigest.indexOf(0x20, oldDigest.indexOf(0x04));
  attribute.set(oldDigest.subarray(marker + 1, marker + 33));
  const oldHex = Buffer.from(attribute).toString('hex').toUpperCase();
  const hexBytes = Buffer.from(oldHex, 'utf8');
  let hexAt = -1;
  for (let index = 0; index + hexBytes.length <= tampered.length; index += 1) {
    if (hexBytes.every((byte, offset) => tampered[index + offset] === byte)) {
      hexAt = index;
      break;
    }
  }
  if (hexAt < 0) throw new Error('the messageDigest attribute was not found in the file');
  tampered.set(Buffer.from(forged, 'utf8'), hexAt);

  // The forged file's own digest comparison now agrees with its own attribute …
  const recomputed = Buffer.from(new Uint8Array(await crypto.subtle.digest('SHA-256', covered())))
    .toString('hex')
    .toUpperCase();
  if (recomputed !== Buffer.from(tampered.subarray(hexAt, hexAt + 64)).toString('utf8')) {
    throw new Error('the check itself failed to forge the attribute');
  }

  // … so only the signature value can catch it.
  const verdicts = await verifySignatures(tampered, undefined);
  const verdict = verdicts[0];
  if (verdict?.integrity !== 'invalid') {
    throw new Error(`a forged messageDigest reads "${String(verdict?.integrity)}"`);
  }
  return `file ${tampered.length} B, digest attribute rewritten to match, verdict ${verdict.integrity}`;
});

await check('independent: OpenSSL verifies the CMS over the signed range', async () => {
  /**
   * The product's own verifier could share a mistake with the product's own writer — a
   * consistently wrong convention satisfies both. So the CMS and the bytes it claims are
   * handed to **OpenSSL**, which knows nothing about this repository: if `cms -verify`
   * accepts the detached signature over exactly the range the dictionary names, the
   * signature is a signature by an outside standard.
   */
  const signature = signatureOf(signed);
  if (signature === null) throw new Error('no signature to hand to OpenSSL');
  const { range, contents } = signature;
  const [start1, length1, start2, length2] = range as number[];
  const covered = Buffer.concat([
    Buffer.from(signed.subarray(start1, start1 + length1)),
    Buffer.from(signed.subarray(start2, start2 + length2)),
  ]);
  writeFileSync(join(dir, 'covered.bin'), covered);
  writeFileSync(join(dir, 'cms.der'), Buffer.from(contents.subarray(0, contents.length)));
  const result = spawnSync(
    'openssl',
    [
      'cms',
      '-verify',
      '-inform',
      'DER',
      '-in',
      'cms.der',
      '-content',
      'covered.bin',
      '-binary',
      '-noverify',
      '-out',
      'nul',
    ],
    {
      cwd: dir,
      encoding: 'utf8',
    },
  );
  if (result.status !== 0) {
    throw new Error(`openssl refused the signature: ${(result.stderr ?? '').slice(0, 200)}`);
  }
  return `openssl cms -verify accepted the detached signature over ${covered.length} covered bytes`;
});

await check('refuse: a wrong password is reported, never silently skipped', async () => {
  try {
    await importPkcs12(new Uint8Array(readFileSync(join(dir, 'identity.p12'))), 'wrong-password');
  } catch (error) {
    const message = String((error as Error)?.message ?? error);
    if (!/password|MAC|integrity/i.test(message))
      throw new Error(`refused with an unhelpful message: ${message}`);
    return `refused: ${message.slice(0, 80)}`;
  }
  throw new Error('a wrong password was accepted');
});

/**
 * A **chain** to check trust against: a local CA and a leaf it signed, both generated by
 * OpenSSL in the check's own directory. Nothing about the chain is ours, which is the
 * point — a trust verdict that only works on certificates this repository made would
 * prove nothing.
 */
function makeChain(): { readonly container: string; readonly ca: string; readonly caDer: Uint8Array } {
  const run = (args: readonly string[]): void => {
    const result = spawnSync('openssl', [...args], { cwd: dir, encoding: 'utf8' });
    if (result.status !== 0)
      throw new Error(`openssl ${args.join(' ')}: ${(result.stderr ?? '').slice(0, 200)}`);
  };
  run([
    'req',
    '-x509',
    '-newkey',
    'rsa:2048',
    '-keyout',
    'ca.key',
    '-out',
    'ca.pem',
    '-days',
    '365',
    '-nodes',
    '-subj',
    '/CN=PDF Editor Check CA',
  ]);
  run([
    'req',
    '-newkey',
    'rsa:2048',
    '-keyout',
    'leaf.key',
    '-out',
    'leaf.csr',
    '-nodes',
    '-subj',
    '/CN=PDF Editor Leaf',
  ]);
  run([
    'x509',
    '-req',
    '-in',
    'leaf.csr',
    '-CA',
    'ca.pem',
    '-CAkey',
    'ca.key',
    '-CAcreateserial',
    '-out',
    'leaf.pem',
    '-days',
    '365',
  ]);
  run([
    'pkcs12',
    '-export',
    '-inkey',
    'leaf.key',
    '-in',
    'leaf.pem',
    '-certfile',
    'ca.pem',
    '-out',
    'leaf.p12',
    '-passout',
    'pass:testpass',
  ]);
  const caDer = new Uint8Array(readFileSync(join(dir, 'ca.pem')));
  const pem = /-----BEGIN CERTIFICATE-----([\s\S]*?)-----END CERTIFICATE-----/.exec(
    new TextDecoder().decode(caDer),
  );
  if (pem === null) throw new Error('the CA certificate did not come back as PEM');
  return {
    container: join(dir, 'leaf.p12'),
    ca: join(dir, 'ca.pem'),
    caDer: new Uint8Array(Buffer.from((pem[1] ?? '').replace(/\s+/g, ''), 'base64')),
  };
}

let chain: ReturnType<typeof makeChain> | null = null;
const chainOnce = (): ReturnType<typeof makeChain> => (chain ??= makeChain());

await check('trust: a leaf signed by an imported root reads trusted, with the path', async () => {
  const built = chainOnce();
  const identity = await importPkcs12(new Uint8Array(readFileSync(built.container)), 'testpass');
  if (identity.chain.length === 0) throw new Error('the PKCS#12 container carried no chain');
  const produced = await signPdf(
    await fixture(),
    { identity, reason: 'Güven denetimi' },
    { signal: new AbortController().signal },
  );
  const verdicts = await verifySignatures(produced.bytes, undefined, { roots: [built.caDer] });
  const verdict = verdicts[0];
  if (verdict?.trust !== 'trusted')
    throw new Error(`trust reads "${String(verdict?.trust)}" with the root imported`);
  if (verdict.trustPath.join(' / ') !== 'PDF Editor Leaf / PDF Editor Check CA') {
    throw new Error(`the path reads "${verdict.trustPath.join(' / ')}"`);
  }
  if (verdict.certificateValidity !== 'valid')
    throw new Error(`validity reads "${verdict.certificateValidity}"`);
  return `trusted via ${verdict.trustPath.join(' → ')}`;
});

await check('trust: the same leaf without any imported root is not called trusted', async () => {
  const built = chainOnce();
  const identity = await importPkcs12(new Uint8Array(readFileSync(built.container)), 'testpass');
  const produced = await signPdf(await fixture(), { identity }, { signal: new AbortController().signal });
  const none = (await verifySignatures(produced.bytes, undefined, { roots: [] }))[0];
  if (none?.trust !== 'not-checked')
    throw new Error(`with no roots the verdict reads "${String(none?.trust)}"`);
  // A *different* root is the interesting case: the chain is attempted and does not reach it.
  const other = await importPkcs12(new Uint8Array(readFileSync(join(dir, 'identity.p12'))), 'testpass');
  const wrong = (await verifySignatures(produced.bytes, undefined, { roots: [other.certificate] }))[0];
  if (wrong?.trust !== 'untrusted')
    throw new Error(`with an unrelated root the verdict reads "${String(wrong?.trust)}"`);
  return 'no roots → not-checked; an unrelated root → untrusted';
});

await check('trust: an expired certificate is named as expired', async () => {
  const built = chainOnce();
  const identity = await importPkcs12(new Uint8Array(readFileSync(built.container)), 'testpass');
  const produced = await signPdf(await fixture(), { identity }, { signal: new AbortController().signal });
  // The clock is passed in: “expired” is a claim about a date, and a check that cannot pin
  // the date is a check that passes for the wrong reason.
  const later = new Date(Date.now() + 400 * 24 * 60 * 60 * 1000);
  const verdict = (
    await verifySignatures(produced.bytes, undefined, { roots: [built.caDer], now: later })
  )[0];
  if (verdict?.certificateValidity !== 'expired')
    throw new Error(`validity reads "${String(verdict?.certificateValidity)}"`);
  if (verdict.certificateNotAfter === null) throw new Error('the expiry date was not reported');
  return `expired as of ${verdict.certificateNotAfter.slice(0, 10)}`;
});

const failed = checks.filter((entry) => !entry.ok);
console.log('');
console.log(`  ${checks.length - failed.length} passed, ${failed.length} failed`);
process.exit(failed.length === 0 ? 0 : 1);
